/*
 * Copyright © 2021-2026 Robert Gordon University
 *
 * This library is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this library. If
 * not, see <https://www.gnu.org/licenses/>.
 */

package rgu.transport.geospatial.multimodal;

import rgu.transport.algorithms.collections.*;
import rgu.transport.algorithms.search.*;
import rgu.transport.algorithms.util.*;
import rgu.transport.util.*;
import rgu.transport.geospatial.*;
import rgu.transport.geospatial.osm.*;

import java.time.*;
import java.util.*;
import java.util.concurrent.atomic.*;
import java.util.function.*;

/**
 * Used to join multiple transit networks to one another, using roads to inform connection times.
 * Connection times will be calculated by walking on the road network, unless there is no road
 * network within a radius around a stop, in which case, the connection times default to as the crow
 * flies.
 *
 * @author Lee A. Christie
 */
public final class NetworkJoiner {

    private final boolean noGraph;
    private final Graph<GeoLocation, Duration> roadDurationGraph;
    private final Collection<TransitNetwork> networks;
    private final Speed speed;
    private final Duration maxTime;
    private final Distance maxDistanceToNearbyRoad;

    private final AtomicReference<TwoDTree<GeoLocation>> tree;

    /**
     * Creates a joiner which will connect multiple transit networks to one another.
     *
     * @param roadGraph the road graph, null if there is no road graph
     * @param tree the 2D tree used as a nearest finder for the road network, null if there is no
     *             road graph or if the neighbour finder should be generated by the Joiner
     * @param networks the collection of one or more transit networks, not null
     * @param speed the walking speed, not null
     * @param maxTime the maximum time to walk between stops on the transit networks, not null
     * @param maxDistanceToNearbyRoad if the nearest road is further away than this, the routing
     *                                uses as the crow flies distance instead of walking on the road
     *                                network, null if there is no limit and road routing should
     *                                always be used
     */
    public NetworkJoiner(Graph<GeoLocation, RoadEdge> roadGraph,
                         TwoDTree<GeoLocation> tree,
                         Collection<TransitNetwork> networks,
                         Speed speed,
                         Duration maxTime,
                         Distance maxDistanceToNearbyRoad) {
        Objects.requireNonNull(networks, "networks");
        Objects.requireNonNull(speed, "speed");
        Objects.requireNonNull(maxTime, "maxTime");
        if (roadGraph == null) {
            HashGraph.Builder<GeoLocation, Duration> builder = HashGraph.builder();
            this.roadDurationGraph = builder.build();
            this.noGraph = true;
        } else {
            this.roadDurationGraph = DurationAdapter.adapt(roadGraph, speed);
            this.noGraph = false;
        }
        if (roadGraph == null) {
            if (tree != null) {
                throw new IllegalArgumentException("roadGraph was null but tree was not null");
            }
            this.tree = null;
        } else {
            if (tree != null) {
                this.tree = new AtomicReference<>(tree);
            } else {
                // defer generating a new nearest finder
                this.tree = new AtomicReference<>();
            }
        }
        this.networks = networks;
        this.speed = speed;
        this.maxTime = maxTime;
        this.maxDistanceToNearbyRoad = maxDistanceToNearbyRoad;
    }

    /**
     * Runs the joiner to produce a joined network.
     *
     * @param consumer callback for edges, can be null if not needed
     * @param consumerArtificial callback for artificial edge, can be null if not needed
     * @param progress the progress listener, not null
     * @param callback the callback to accept the result of joining
     * @throws InterruptedException if the thread is interrupted
     */
    public void run(BiConsumer<GeoLocation, GeoLocation> consumer,
                    BiConsumer<GeoLocation, GeoLocation> consumerArtificial,
                    ProgressListener progress,
                    Consumer<TransitNetwork> callback) throws InterruptedException {

        // get all network locations in one set
        Set<GeoLocation> networkLocations = GeoLocations.allLocations(networks);

        Thread joinerThread = Thread.currentThread();
        progress.setCancelAction(() -> {
            joinerThread.interrupt();
        });

        TwoDTree<GeoLocation> tree;
        if (this.tree == null) {
            tree = null;
        } else {
            TwoDTree<GeoLocation> reference = this.tree.get();
            if (reference != null) {
                tree = reference;
            } else {
                progress.onNewStage("Pre-processing road vertices...");
                tree = TwoDTree.of(Set.copyOf(this.roadDurationGraph.vertices()),
                        progress, true);
                this.tree.set(tree);
            }
        }


        // mapping of network locations to nearest road point
        Map<GeoLocation, GeoLocation> nearestMapping;
        if (this.noGraph) {
            nearestMapping = new HashMap<>();
        } else {
            progress.onNewStage("Connecting to roads...");
            nearestMapping = GeoLocations.findWithTwoDTree(tree, networkLocations, progress, true);
        }

        // remove non-connected points if there is a limit to nearest road
        if (maxDistanceToNearbyRoad != null) {
            progress.onNewStage("Checking for points without roads...");
            int i = 0;
            int n = nearestMapping.size();
            progress.onUpdateProgress(i / (double) n);
            for (GeoLocation key : new HashSet<>(nearestMapping.keySet())) {
                ThreadUtil.checkInterrupt();
                GeoLocation value = nearestMapping.get(key);
                if (GeoLocation.HAVERSINE.distance(key, value)
                        .compareTo(maxDistanceToNearbyRoad) > 0) {
                    nearestMapping.remove(key);
                }
                i++;
                progress.onUpdateProgress(i / (double) n);
            }
            progress.onUpdateProgress(1.0);
        }

        // reverse mapping for points on road which are nearest for one or more points on networks
        progress.onNewStage("Reversing network-to-road mapping...");
        int i = 0;
        int n = nearestMapping.size();
        progress.onUpdateProgress(i / (double) n);
        Map<GeoLocation, List<GeoLocation>> nearestReverseMapping = new HashMap<>();
        for (Map.Entry<GeoLocation, GeoLocation> entry : nearestMapping.entrySet()) {
            ThreadUtil.checkInterrupt();
            GeoLocation actual = entry.getKey();
            GeoLocation nearest = entry.getValue();
            if (nearestReverseMapping.containsKey(nearest)) {
                nearestReverseMapping.get(nearest).add(actual);
            } else {
                List<GeoLocation> newList = new ArrayList<>(1);
                newList.add(actual);
                nearestReverseMapping.put(nearest, newList);
            }
            i++;
            progress.onUpdateProgress(i / (double) n);
        }
        progress.onUpdateProgress(1.0);

        // all the points on road network which are "nearest" to at least 1
        // point (maybe more) on at least one transit network
        Set<GeoLocation> allNearest = new HashSet<>(nearestMapping.values());

        // algorithm for finding reachable neighbours
        Dijkstra<Duration> dijkstra = Dijkstra.ofDuration();

        // matrix of distances between pairs of points where distance > 5 min.
        // (for a -> a, the value is zero seconds)
        progress.onNewStage("Searching connections...");
        Map<GeoLocation, Map<GeoLocation, Duration>> matrixNearestToNearest
                = findReachable(allNearest, roadDurationGraph, dijkstra, maxTime, progress);

        // matrix of above but between actual transit points, not "nearest".
        // (for a -> a, the value is not present)
        // points are not included if there is no nearest road point within the time limit
        progress.onNewStage("Route finding on road graph...");
        Map<GeoLocation, Map<GeoLocation, Duration>> matrixStopToStop
                = addJoiningEdges(matrixNearestToNearest, nearestReverseMapping,
                                  GeoLocation.HAVERSINE, speed, maxTime, progress);

        // add non-connected points if there is a limit to nearest road
        // (for a -> a, the value is not present)
        if (maxDistanceToNearbyRoad != null) {
            progress.onNewStage("Route finding for points with no nearby roads...");
            readdNonRoadConnectedPoints(matrixStopToStop, networkLocations, nearestMapping.keySet(),
                                        GeoLocation.HAVERSINE, speed, maxTime, progress);
        }

        // combine everything
        TransitNetwork.Builder builder = TransitNetwork.copyAll(networks, consumer);
        for (var outer : matrixStopToStop.entrySet()) {
            ThreadUtil.checkInterrupt();
            GeoLocation a = outer.getKey();
            for (var inner : outer.getValue().entrySet()) {
                GeoLocation b = inner.getKey();
                Duration duration = inner.getValue();
                builder.addArtificialEdge(a, b, duration);
                if (consumerArtificial != null) {
                    consumerArtificial.accept(a, b);
                }
            }
        }

        TransitNetwork network = builder.build();

        progress.onCompletion();

        // return the result
        callback.accept(network);

    }

    private static Map<GeoLocation, Map<GeoLocation, Duration>> findReachable(
            Set<GeoLocation> nearestSet,
            Graph<GeoLocation, Duration> roadGraph,
            Dijkstra<Duration> dijkstra,
            Duration maxTime,
            ProgressListener progress) throws InterruptedException {
        Map<GeoLocation, Map<GeoLocation, Duration>> rv = new HashMap<>();
        int numDone = 0;
        double total = nearestSet.size();
        progress.onUpdateProgress(0.0);
        for (GeoLocation aPrime : nearestSet) {
            ThreadUtil.checkInterrupt();
            Map<GeoLocation, Duration> currentRow = new HashMap<>();
            dijkstra.reachable(roadGraph, aPrime, maxTime, ReachabilityCallback.from(
                    (location, duration) -> {
                if (nearestSet.contains(location)) {
                    currentRow.put(location, duration);
                }
            }));
            rv.put(aPrime, currentRow);
            numDone++;
            progress.onUpdateProgress(numDone / total);
        }
        progress.onUpdateProgress(1.0);
        return rv;
    }

    private Map<GeoLocation, Map<GeoLocation, Duration>> addJoiningEdges(
            Map<GeoLocation, Map<GeoLocation, Duration>> matrixNearestToNearest,
            Map<GeoLocation, List<GeoLocation>> nerestReverseMapping,
            Metric<GeoLocation, Distance> metric,
            Speed speed,
            Duration maxTime,
            ProgressListener progress) throws InterruptedException {

        // result
        Map<GeoLocation, Map<GeoLocation, Duration>> rv = new HashMap<>();

        int i = 0;
        double n = matrixNearestToNearest.size();
        progress.onUpdateProgress(i / n);

        // all aPrime in the matrix
        for (GeoLocation aPrime : matrixNearestToNearest.keySet()) {

            // all bPrime reachable form aPrime in the matrix (note: includes a == b)
            for (GeoLocation bPrime : matrixNearestToNearest.get(aPrime).keySet()) {

                ThreadUtil.checkInterrupt();

                // duration aPrime to bPrime
                Duration aPrimeToBPrime = matrixNearestToNearest.get(aPrime).get(bPrime);

                // all a connected to aPrime
                for (GeoLocation a : nerestReverseMapping.get(aPrime)) {

                    // duration from a to aPrime
                    Duration aToAPrime = speed.timeTruncatedToSeconds(metric.distance(a, aPrime));

                    // duration from a to bPrime
                    Duration aToBPrime = aPrimeToBPrime.plus(aToAPrime);

                    // all b connected to bPrime
                    for (GeoLocation b : nerestReverseMapping.get(bPrime)) {

                        // skip a == b
                        if (!a.equals(b)) {

                            // duration from b to bPrime
                            Duration bPrimeToB = speed.timeTruncatedToSeconds(
                                metric.distance(bPrime, b));

                            // duration from a to b
                            Duration aToB = aToBPrime.plus(bPrimeToB);

                            // still inside the max time window?
                            if (aToB.compareTo(maxTime) <= 0) {

                                // Add a -> b, aToB to result
                                if (rv.containsKey(a)) {
                                    rv.get(a).put(b, aToB);
                                } else {
                                    Map<GeoLocation, Duration> newMap = new HashMap<>();
                                    newMap.put(b, aToB);
                                    rv.put(a, newMap);
                                }

                            }

                        }

                    }

                }

            }

            i++;
            progress.onUpdateProgress(i / n);

        }

        progress.onUpdateProgress(1.0);

        // return the result
        return rv;

    }

    private static void readdNonRoadConnectedPoints(
            Map<GeoLocation, Map<GeoLocation, Duration>> rv,
            Set<GeoLocation> allLocations,
            Set<GeoLocation> onlyLocationsWhichDoHaveNearest,
            Metric<GeoLocation, Distance> metric,
            Speed speed,
            Duration maxTime,
            ProgressListener progress) {

        Set<GeoLocation> onlyLocationsWhichDoNotHaveNearest = new HashSet<>();
        for (GeoLocation loc : allLocations) {
            if (!onlyLocationsWhichDoHaveNearest.contains(loc)) {
                onlyLocationsWhichDoNotHaveNearest.add(loc);
            }
        }

        int i = 0;
        double n = onlyLocationsWhichDoNotHaveNearest.size();
        progress.onUpdateProgress(i / n);

        // loop over all points without nearby roads
        for (GeoLocation a : onlyLocationsWhichDoNotHaveNearest) {

            // and for each point (all others)
            for (GeoLocation b : allLocations) {

                // skip a -> a
                if (!a.equals(b)) {

                    // if the crow-flys time is within the limit
                    Distance distance = metric.distance(a, b);
                    Duration time = speed.timeTruncatedToSeconds(distance);
                    if (time.compareTo(maxTime) <= 0) {

                        // Add a -> b, time to result
                        if (rv.containsKey(a)) {
                            rv.get(a).put(b, time);
                        } else {
                            Map<GeoLocation, Duration> newMap = new HashMap<>();
                            newMap.put(b, time);
                            rv.put(a, newMap);
                        }

                    }

                }

            }

            i++;
            progress.onUpdateProgress(i / n);

        }

        progress.onUpdateProgress(1.0);

    }

}
